### ISSUE TITLE
在build-thirdparty.sh中export LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by crcc** [baidu/palo#10]
mkdir -p $TP_DIR/src
mkdir -p $TP_DIR/installed （52行）
export LD_LIBRARY_PATH=$TP_DIR/installed/lib #加上这一行

要不当本地没有libcrypto.so.1.0.0库时，配置thrift会报错

===== begin build thrift-0.9.3
/home/crc/palo/thirdparty/..//thirdparty/src/thrift-0.9.3
/home/crc/palo/thirdparty/..//thirdparty/installed/lib
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '1000' is supported by ustar format... yes
checking whether GID '1000' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/home/crc/palo/thirdparty/src/thrift-0.9.3':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

在config.log里面有一行
./conftest error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

**Comment by morningman** [comment]
谢谢提供解决方案，我们内部会测试下，然后进行更改~

**Comment by cyongli** [comment]
thrift是需要libcrypto.so.1.0.0这个的，我们在第三方库中已经编译libssl时候编译了，你不需要export LD_LIBRARY_PATH

**Comment by crcc** [comment]
还是改成export LD_LIBRARY_PATH=$TP_DIR/installed/lib:$LD_LIBRARY_PATH吧。我本地的LD_LIBRARY_PATH是空的，其他人的也许设置了。

**Comment by interma** [comment]
PR is welcome... 😆
