### ISSUE TITLE
Unknown database 'default_cluster:bddatabase'

### ISSUE THREAD

**Issue by niuAlex** [baidu/palo#100]
Cluster 名字：bdcluster ， 数据库：bddatabase  
通过 java和 navicat 连接的时候报错 Unknown database 'default_cluster:bddatabase'， 不知道该如何制定连接串

**Comment by morningman** [comment]
用户名加上 @clustername  举例：username@bdcluster

**Comment by niuAlex** [comment]
3q， 可以了 ~
