### ISSUE TITLE
三台alived ,但是报错ERROR 1050 (42S01): Failed to find enough host in all backends. need: 3

### ISSUE THREAD

**Issue by alexliu5678** [baidu/palo#112]
CREATE TABLE ssb.lineorder ( 
    lo_orderkey BIGINT, 
    lo_linenumber BIGINT, 
    lo_custkey INT, 
    lo_partkey INT, 
    lo_suppkey INT, 
    lo_orderdate INT,  
    lo_orderpriotity VARCHAR(16) REPLACE,  
    lo_shippriotity INT SUM, 
    lo_quantity BIGINT SUM, 
    lo_extendedprice BIGINT SUM, 
    lo_ordtotalprice BIGINT SUM, 
    lo_discount BIGINT SUM, 
    lo_revenue BIGINT SUM, 
    lo_supplycost BIGINT SUM, 
    lo_tax BIGINT SUM, 
    lo_commitdate BIGINT SUM, 
    lo_shipmode VARCHAR(11) REPLACE )  
    DISTRIBUTED BY RANDOM;

mysql> SHOW PROC '/backends' ;
+-----------------+-----------+--------------+-----------------------------------+---------------+--------+----------+---------------------+---------------------+-------+----------------------+-----------------------+-----------+
| Cluster         | BackendId | IP           | HostName                          | HeartbeatPort | BePort | HttpPort | LastStartTime       | LastHeartbeat       | Alive | SystemDecommissioned | ClusterDecommissioned | TabletNum |
+-----------------+-----------+--------------+-----------------------------------+---------------+--------+----------+---------------------+---------------------+-------+----------------------+-----------------------+-----------+
| default_cluster | 10001     | 192.168.4.67 | db86-test-qc1                     | 9050          | 9060   | 8040     | 2017-09-21 11:29:54 | 2017-09-21 17:09:15 | true  | false                | true                  | 10        |
| default_cluster | 10002     | 192.168.4.69 | db88-test-qc1                     | 9050          | 9060   | 8040     | 2017-09-21 11:40:14 | 2017-09-21 17:09:15 | true  | false                | false                 | 23        |
| default_cluster | 10003     | 192.168.4.67 | db86-test-qc1                     | 9060          | -1     | -1       | N/A                 | N/A                 | false | false                | false                 | 0         |
| default_cluster | 10004     | 192.168.4.37 | qc1-testenv3-tomcat-quantgroup.cn | 9050          | 9060   | 8040     | 2017-09-21 16:19:34 | 2017-09-21 17:09:15 | true  | false                | false                 | 27        |
+-----------------+-----------+--------------+-----------------------------------+---------------+--------+----------+---------------------+---------------------+-------+----------------------+-----------------------+-----------+
4 rows in set (0.00 sec)

**Comment by morningman** [comment]
建表默认是3副本，3副本的表，必须有至少3台独立的物理机（不同ip），只是有3个BE是不够的。方便的话可以加下微信 morningman-cmy，交流更及时。
