### ISSUE TITLE
hdfs 导入 palo

### ISSUE THREAD

**Issue by niuAlex** [baidu/palo#120]
hi 各位好， hdfs文件导入到palo 遇到点问题
1：要求提供bin/hadoop。  这个在什么地方可以配置的么？ 我用ln -s 方式解决了
2：2017-09-28 18:23:41,627 INFO 2533 [DppScheduler.submitEtlJob():201] Error: Could not find or load main class bistreaming

还有 有技术群没？ 谢谢了

**Comment by imay** [comment]
HDFS导入需要部署HDFS Broker，可以参见我们文档。

需要加入Palo微信技术讨论群的，请加微信号：myh13161636186，然后备注一下：加入Palo技术讨论群

**Comment by morningman** [comment]
该问题已解决：
1. 用户使用的是默认的 hadoop load 方式，该方式目前github版本不提供，只提供百度内部使用。
2. 外部用户可以使用 通过 http 方式导入本地文件的 mini load 方式（help mini load）。也可以通过 broker 读取 hdfs 或者 baidu bos 的数据进行导入（详见 help load 中的 broker相关部分）
