### ISSUE TITLE
sudo: updatedb：找不到命令

### ISSUE THREAD

**Issue by lonly197** [baidu/palo#139]
在 install 文档的第一节（系统依赖）中，提到在安装完cmake等依赖包后需要执行“updatedb”操作，但该命令，不管是Ubuntu，还是CentOS都没有自带的，需要安装mlocate包，命令才生效。

**Comment by morningman** [comment]
感谢反馈，已更新到 https://github.com/baidu/palo/wiki/Palo-Install
