### ISSUE TITLE
第三方库编译失败

### ISSUE THREAD

**Issue by lonly197** [baidu/palo#140]
## 编译环境：

Linux dmp1 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

## 编译版本：

Branch：Master

Last Commit：44ed16cd23797137ba08f62a7e66fad7a87b3abf

## 错误信息：

截图是编译失败的详细信息：

![image](https://user-images.githubusercontent.com/7350356/32882030-00117130-caee-11e7-810d-7b66cc510181.png)

**Comment by morningman** [comment]
在 install.md 的常见问题中，有这个问题的解决方法。

**Comment by lonly197** [comment]
我按照install.md 的【常见问题】操作，但问题依旧。

![image](https://user-images.githubusercontent.com/7350356/32883062-44fef4e0-caf1-11e7-99be-04fd635bba5c.png)

以是tra again的错误信息：

![image](https://user-images.githubusercontent.com/7350356/32883098-65702794-caf1-11e7-975b-397c46e8de1f.png)

这是我系统的gcc版本：

![image](https://user-images.githubusercontent.com/7350356/32883130-7a919a54-caf1-11e7-8ff1-c17d50b9895b.png)
