### ISSUE TITLE
tutorial mismatch description

### ISSUE THREAD

**Issue by wuyunfeng** [baidu/palo#143]
https://github.com/baidu/palo/blob/master/docs/user_guide/tutorial.md

示例：以 "table2_20170707"为Label，使用HDFS上的文件导入table2表

LOAD LABEL **table1_20170707**
(
    DATA INFILE("hdfs://your.namenode.host:port/dir/table2_data")
    INTO TABLE table2
)
WITH BROKER hdfs ("username"="hdfs_user", "password"="hdfs_password")
PROPERTIES
(
    "timeout"="3600",
    "max_filter_ratio"="0.1"
);

**table1_20170707** should be **table2_20170707**

**Comment by morningman** [comment]
Done
