### ISSUE TITLE
About sort field of non-aggregation table sql statement

### ISSUE THREAD

**Issue by interma** [baidu/palo#15]
In https://github.com/baidu/palo/blob/master/README.md:

> In non-aggregation type of table, columns are not distinguished between dimensions and metrics, but should specify the sort columns in order to sort all rows. Palo will sort the table data according to the sort columns without any aggregation. The following figure gives an example of creating non-aggregation table.
```
-- Create non-aggregation table --
CREATE TABLE example_tbl (
    `date`      DATE,
    id          BIGINT,
    country     VARCHAR(32),
    click       BIGINT,
    cost        BIGINT
) DUPLICATE KEY(`date`, id, country)
DISTRIBUTED BY HASH(id) BUCKETS 32;
```

> should specify the sort columns in order to sort all rows

Question: 
where is the sort column in sql statement? I assumed it should be like:
`date      DATE Sort,`
right? Is there something missing?

**Comment by interma** [comment]
@imay thanks, clearly.

PS: 
As we talked in wechat group, you can give a *question* label to this issue.

**Comment by imay** [comment]
thanks for advise
