### ISSUE TITLE
查询frontends时报错，版本release-0.8.1

### ISSUE THREAD

**Issue by yuanfeng0905** [baidu/palo#190]
mysql> show proc '/frontends';
ERROR 1064 (HY000): (JE 6.2.31) Problem communicating with master.

docker版本：
Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: <unknown>
 Go version:      go1.8.3
 Git commit:      774336d/1.13.1
 Built:           Wed Mar  7 17:06:16 2018
 OS/Arch:         linux/amd64
 Experimental:    false

**Comment by morningman** [comment]
可能需要检查leader fe 节点是否运行正常
