### ISSUE TITLE
PALO的明细模型

### ISSUE THREAD

**Issue by peiss** [baidu/palo#197]
请问PALO支持明细模型吗，可以查询明细数据吗？

看到 了文章：https://blog.bcmeng.com/post/apache-kylin-vs-baidu-palo.html
请问下PALO的明细模型的实现细节，只是对KEY进行了排序来实现的吗？

是不是说相当于前缀索引，如果字段列分别是KA、KB、KC。。。，那是不是查询的时候一定得包含KA，或者按顺序筛选才可以？
如果只查询KB，是不是就会全表查询用不到这个排序索引？

**Comment by morningman** [comment]
是否能查询明细，取决你的列的定义和聚合方式的选择。比如在指标列上选择了sum的聚合方式。那么Palo会将维度列相同的行，在指标列上做求和存储。假设你每一行都有一个UniqID作为维度列，那么就相当于保证了没有任意两行的维度列是相同的，那么Palo也就不会进行聚合，这样，明细数据就保留下来了。

Palo存储的数据是按Key进行排序的，但是这个和明细数据没有关系。如果按照排序列的前缀进行查询，效率会比较高。

**Comment by peiss** [comment]
谢谢
