### ISSUE TITLE
palo master分支编译失败

### ISSUE THREAD

**Issue by saga1015** [baidu/palo#201]
你好，我编译master分支时，第三方的软件包编译都OK
编译器 GCC 4.8.2
cmake版本  3.0.2
当执行./build.sh后，编译出现如下错误
[  3%] Building CXX object src/exec/CMakeFiles/Exec.dir/exec_node.cpp.o
In file included from /root/palo/be/src/olap/aggregate_func.h:21:0,
                 from /root/palo/be/src/olap/field.h:21,
                 from /root/palo/be/src/runtime/vectorized_row_batch.h:23,
                 from /root/palo/be/src/exec/olap_scanner.h:33,
                 from /root/palo/be/src/exec/olap_scan_node.h:30,
                 from /root/palo/be/src/exec/exec_node.cpp:47:
/root/palo/be/src/olap/types.h: In static member function ‘static std::string palo::FieldTypeTraits<(palo::FieldType)9u>::to_string(char*)’:
/root/palo/be/src/olap/types.h:410:65: error: expected ‘)’ before ‘PRIu64’
                 current += snprintf(current, end - current, "%" PRIu64, prefix);
                                                                 ^
/root/palo/be/src/olap/types.h:410:79: warning: spurious trailing ‘%’ in format [-Wformat=]
                 current += snprintf(current, end - current, "%" PRIu64, prefix);
                                                                               ^
/root/palo/be/src/olap/types.h:410:79: warning: too many arguments for format [-Wformat-extra-args]
/root/palo/be/src/olap/types.h:410:79: warning: spurious trailing ‘%’ in format [-Wformat=]
/root/palo/be/src/olap/types.h:410:79: warning: too many arguments for format [-Wformat-extra-args]
/root/palo/be/src/olap/types.h:411:68: error: expected ‘)’ before ‘PRIu64’
                 current += snprintf(current, end - current, "%.19" PRIu64, middle);
                                                                    ^
/root/palo/be/src/olap/types.h:411:82: warning: conversion lacks type at end of format [-Wformat=]
                 current += snprintf(current, end - current, "%.19" PRIu64, middle);
                                                                                  ^
/root/palo/be/src/olap/types.h:411:82: warning: too many arguments for format [-Wformat-extra-args]
/root/palo/be/src/olap/types.h:411:82: warning: conversion lacks type at end of format [-Wformat=]
/root/palo/be/src/olap/types.h:411:82: warning: too many arguments for format [-Wformat-extra-args]
/root/palo/be/src/olap/types.h:412:68: error: expected ‘)’ before ‘PRIu64’
                 current += snprintf(current, end - current, "%.19" PRIu64, suffix);
                                                                    ^
/root/palo/be/src/olap/types.h:412:82: warning: conversion lacks type at end of format [-Wformat=]
                 current += snprintf(current, end - current, "%.19" PRIu64, suffix);
                                                                                  ^
/root/palo/be/src/olap/types.h:412:82: warning: too many arguments for format [-Wformat-extra-args]
/root/palo/be/src/olap/types.h:412:82: warning: conversion lacks type at end of format [-Wformat=]
/root/palo/be/src/olap/types.h:412:82: warning: too many arguments for format [-Wformat-extra-args]
/root/palo/be/src/olap/types.h:414:65: error: expected ‘)’ before ‘PRIu64’
                 current += snprintf(current, end - current, "%" PRIu64, middle);
                                                                 ^
/root/palo/be/src/olap/types.h:414:79: warning: spurious trailing ‘%’ in format [-Wformat=]
                 current += snprintf(current, end - current, "%" PRIu64, middle);
                                                                               ^
/root/palo/be/src/olap/types.h:414:79: warning: too many arguments for format [-Wformat-extra-args]
/root/palo/be/src/olap/types.h:414:79: warning: spurious trailing ‘%’ in format [-Wformat=]
/root/palo/be/src/olap/types.h:414:79: warning: too many arguments for format [-Wformat-extra-args]
/root/palo/be/src/olap/types.h:415:68: error: expected ‘)’ before ‘PRIu64’
                 current += snprintf(current, end - current, "%.19" PRIu64, suffix);
                                                                    ^
/root/palo/be/src/olap/types.h:415:82: warning: conversion lacks type at end of format [-Wformat=]
                 current += snprintf(current, end - current, "%.19" PRIu64, suffix);
                                                                                  ^
/root/palo/be/src/olap/types.h:415:82: warning: too many arguments for format [-Wformat-extra-args]
/root/palo/be/src/olap/types.h:415:82: warning: conversion lacks type at end of format [-Wformat=]
/root/palo/be/src/olap/types.h:415:82: warning: too many arguments for format [-Wformat-extra-args]
/root/palo/be/src/olap/types.h:417:65: error: expected ‘)’ before ‘PRIu64’
                 current += snprintf(current, end - current, "%" PRIu64, suffix);
                                                                 ^
/root/palo/be/src/olap/types.h:417:79: warning: spurious trailing ‘%’ in format [-Wformat=]
                 current += snprintf(current, end - current, "%" PRIu64, suffix);
                                                                               ^
/root/palo/be/src/olap/types.h:417:79: warning: too many arguments for format [-Wformat-extra-args]
/root/palo/be/src/olap/types.h:417:79: warning: spurious trailing ‘%’ in format [-Wformat=]
/root/palo/be/src/olap/types.h:417:79: warning: too many arguments for format [-Wformat-extra-args]
make[2]: *** [src/exec/CMakeFiles/Exec.dir/exec_node.cpp.o] 错误 1
make[1]: *** [src/exec/CMakeFiles/Exec.dir/all] 错误 2
make: *** [all] 错误 2

请问大拿们，这个如何解决？

**Comment by cyongli** [comment]
https://github.com/Microsoft/rDSN/issues/197

**Comment by saga1015** [comment]
昨天编译是在centos6上编译的，今天安装了centos 7.5 minimal版本，然后安装了一些有依赖，第三方的包编译都没问题，在./build.sh后，到最后的啥时候报错了
[100%] Building CXX object src/service/CMakeFiles/palo_be.dir/palo_main.cpp.o
Linking CXX executable palo_be
/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
make[2]: *** [src/service/palo_be] Error 1
make[1]: *** [src/service/CMakeFiles/palo_be.dir/all] Error 2
make: *** [all] Error 2

我检查了libstdc++.so，我也建立了软连接，但是还是报错，怎么解决呢，大拿

**Comment by saga1015** [comment]
解决了，必须安装libstdc++-static这个包才可以

**Comment by morningman** [comment]
感谢提供解决方案
