### ISSUE TITLE
复杂查询be挂掉

### ISSUE THREAD

**Issue by yuanfeng0905** [baidu/palo#204]
您好：

在我们的使用场景里，想使用plao直接做ETL，在某个复杂查询中，发现be直接扑街，看be.INFO日志，发现有一行：

**W0613 11:38:51.535336   312 olap_scan_node.cpp:753] Predicate value num 2253 excede limit 1024**

看日志应该是SQL语句太复杂导致超出了系统谓词下推数量限制？
那palo是否能用于常规ETL场景，还是只能用于OLAP分析场景？

os: centos7.2 
palo version: 0.8.1

**Comment by imay** [comment]
这个log不是导致程序挂掉的原因。
可以把程序挂掉时候的堆栈打印出来，我们这边看一下

**Comment by yuanfeng0905** [comment]
be.out输出的异常堆栈信息：

*** Aborted at 1528864101 (unix time) try "date -d @1528864101" if you are using GNU date ***
PC: @           0xb9242a palo::TupleIsNullPredicate::get_boolean_val()
*** SIGSEGV (@0x0) received by PID 222 (TID 0x7f5008be5700) from PID 0; stack trace: ***
    @     0x7f5033b0d100 (unknown)
    @           0xb9242a palo::TupleIsNullPredicate::get_boolean_val()
    @           0xbcb4c5 palo::IfExpr::get_string_val()
    @           0xb64c92 palo::Expr::get_const_val()
    @           0xb7c9af palo::ScalarFnCall::open()
    @           0xb62de0 palo::Expr::open()
    @           0xb62de0 palo::Expr::open()
    @           0xb7c80e palo::ScalarFnCall::open()
    @           0xb6befc palo::ExprContext::open()
    @           0xb62fae palo::Expr::open()
    @           0xf7cbaa palo::HashJoinNode::open()
    @           0xd17165 palo::PlanFragmentExecutor::open_internal()
    @           0xd17d87 palo::PlanFragmentExecutor::open()
    @           0xce0eaf palo::FragmentExecState::execute()
    @           0xce1d30 palo::FragmentMgr::exec_actual()
    @           0xce497e boost::detail::function::void_function_obj_invoker0<>::invoke()
    @           0xcc06db palo::ThreadPool::work_thread()
    @          0x10de395 thread_proxy
    @     0x7f5033b05dc5 start_thread
    @     0x7f503353121d __clone

**Comment by yuanfeng0905** [comment]
@imay 麻烦看下。

**Comment by imay** [comment]
可以把你的查询贴一下么？我们这边尝试复现下

**Comment by yuanfeng0905** [comment]
SELECT if(flow.datetime is null,
        oder.datetime,
        flow.datetime),
        if(flow.date is null,
        oder.date,
        flow.date),
        if(flow.hourly_grain is null,
        oder.hourly_grain,
        flow.hourly_grain),
         if(flow.website_id is null,
        oder.website_id,
        flow.website_id),
        if(flow.platform_id is null,
        oder.platform_id,
        flow.platform_id),
         if(oder.sku_order_num is null,
        0,
        oder.sku_order_num),
        if(oder.ref_order_num is null,
        0,
        oder.ref_order_num),
         if(oder.ref_amount is null,
        0,
        oder.ref_amount),
        if(oder.sku_paid_num is null,
        0,
        oder.sku_paid_num),
         if(oder.paid_order_num is null,
        0,
        oder.paid_order_num),
        if(oder.paid_amount is null,
        0,
        oder.paid_amount),
         if(flow.page_pv is null,
        0,
        flow.page_pv),
        if(flow.page_uv is null,
        0,
        flow.page_uv),
        if(flow.page_cart_uv is null,
        0,
        flow.page_cart_uv),
         if(flow.page_checkout_uv is null,
        0,
        flow.page_checkout_uv),
        if(flow.page_product_pv is null,
        0,
        flow.page_product_pv),
        if(flow.page_product_uv is null,
        0,
        flow.page_product_uv),
         if(flow.sku_cart_num is null,
        0,
        flow.sku_cart_num),
        if(flow.session_viewproduct_count is null,
        0,
        flow.session_viewproduct_count),
        if(flow.session_viewproduct_out_count is null,
        0,
        flow.session_viewproduct_out_count)
FROM dm__bi.profile_report flow full outer
JOIN 
  (SELECT if(tc.`datetime` is null,
        tp.`datetime`,
        tc.`datetime`) AS `datetime`,
         if(tc.date is null,
        tp.date,
        tc.date) AS date,
         if(tc.hourly_grain is null,
        tp.hourly_grain,
        tc.hourly_grain) AS hourly_grain,
         if(tc.website_id is null,
        tp.website_id,
        tc.website_id) AS website_id,
         if(tc.platform_id is null,
        tp.platform_id,
        tc.platform_id) AS platform_id,
         if(tc.sku_num is null,
        0,
        tc.sku_num) AS sku_order_num,
         if(tc.`count` is null,
        0,
        tc.`count`) AS ref_order_num,
         if(round((tc.amount * cer.rate),
        4) is null,
        0,
        round((tc.amount * cer.rate),
        4)) AS ref_amount,
         if(tp.sku_num is null,
        0,
        tp.sku_num) AS sku_paid_num,
         if(tp.`count` is null,
        0,
        tp.`count`) AS paid_order_num,
         if(round((tp.amount * cer.rate),
        4) is null,
        0,
        round((tp.amount * cer.rate),
        4)) AS paid_amount
  FROM ( 
    (SELECT '37' AS website_id,
        CASE
        WHEN order_source = 'android_app' THEN
        3
        WHEN order_source = 'ios_app' THEN
        4
        WHEN order_source = 'mobile_web' THEN
        2
        WHEN order_source = 'mobile_pc_web' THEN
        2
        WHEN order_source = 'wechat' THEN
        5
        ELSE 1
        END AS platform_id, hour(hours_add(sfo.created_at,8)) AS hourly_grain, cast(regexp_replace(date(hours_add(sfo.created_at,8)),'-','') AS int) AS `date`, DATE_FORMAT(hours_add(sfo.created_at,8),'%Y%m%d%H') AS `datetime`, max(sfo.order_currency_code) AS order_currency_code, sum(sfoi.qty_ordered) AS sku_num,max(sfo.grand_total) AS amount,count(distinct sfoi.order_id) AS `count`
    FROM ods__babyhaven__babyhaven.sales_flat_order sfo
    JOIN ods__babyhaven__babyhaven.sales_flat_order_item sfoi
        ON (sfoi.order_id = sfo.entity_id)
    WHERE hours_add(sfo.created_at,8) >= '2018-05-01 00:00:00'
            AND hours_add(sfo.created_at,8) < '2018-06-01 00:00:00'
    GROUP BY  `datetime`,date,hourly_grain,platform_id ) ) tc full outer
    JOIN ( 
      (SELECT '37' AS website_id,
          CASE
          WHEN order_source = 'android_app' THEN
          3
          WHEN order_source = 'ios_app' THEN
          4
          WHEN order_source = 'mobile_web' THEN
          2
          WHEN order_source = 'mobile_pc_web' THEN
          2
          WHEN order_source = 'wechat' THEN
          5
          ELSE 1
          END AS platform_id, hour(hours_add(sfo.paid_at,8)) AS hourly_grain, cast(regexp_replace(date(hours_add(sfo.paid_at,8)),'-','') AS int) AS `date`, DATE_FORMAT(hours_add(sfo.paid_at,8),'%Y%m%d%H') AS `datetime`, max(sfo.order_currency_code) AS order_currency_code, sum(sfoi.qty_ordered) AS sku_num,max(sfo.grand_total) AS amount,count(distinct sfoi.order_id) AS `count`
      FROM ods__babyhaven__babyhaven.sales_flat_order sfo
      JOIN ods__babyhaven__babyhaven.sales_flat_order_item sfoi
          ON (sfoi.order_id = sfo.entity_id)
      WHERE hours_add(sfo.paid_at,8) >= '2018-05-01 00:00:00'
              AND hours_add(sfo.paid_at,8) < '2018-06-01 00:00:00'
      GROUP BY  `datetime`,date,hourly_grain,platform_id ) ) tp
          ON (tc.website_id = tp.website_id
              AND tc.platform_id = tp.platform_id
              AND tc.hourly_grain = tp.hourly_grain
              AND tc.date = tp.date)
      LEFT JOIN dm__bi.currency_exchange_rate cer
          ON (cer.currency_code = tc.order_currency_code
              AND cer.date = floor(tc.`date`/100)) ) oder
        ON (oder.date = flow.date
            AND oder.hourly_grain = flow.hourly_grain
            AND oder.website_id = flow.website_id
            AND oder.platform_id = flow.platform_id)
  WHERE flow.datetime >= 2018050100
        AND flow.datetime < 2018060100 limit 10

**Comment by chenhao7253886** [comment]
麻烦把你的建表语句发一下。

**Comment by yuanfeng0905** [comment]
CREATE TABLE `profile_report` (
  `datetime` int(11) NOT NULL COMMENT "时间 2018060601",
  `website_id` tinyint(4) NOT NULL COMMENT "站点id",
  `platform_id` tinyint(4) NOT NULL COMMENT "平台id",
  `date` int(11) NOT NULL COMMENT "日期 20180606",
  `hourly_grain` tinyint(4) NOT NULL COMMENT "小时",
  `ref_order_num` int(11) REPLACE DEFAULT "0" COMMENT "订单数",
  `paid_order_num` int(11) REPLACE DEFAULT "0" COMMENT "支付订单数",
  `ref_amount` decimal(20, 4) REPLACE DEFAULT "0" COMMENT "订单金额",
  `paid_amount` decimal(20, 4) REPLACE DEFAULT "0" COMMENT "支付订单金额",
  `page_pv` int(11) REPLACE DEFAULT "0" COMMENT "页面pv",
  `page_uv` int(11) REPLACE DEFAULT "0" COMMENT "页面uv",
  `page_cart_uv` int(11) REPLACE DEFAULT "0" COMMENT "购物车uv",
  `page_checkout_uv` int(11) REPLACE DEFAULT "0" COMMENT "提交订单uv",
  `page_product_pv` int(11) REPLACE DEFAULT "0" COMMENT "商详页pv",
  `page_product_uv` int(11) REPLACE DEFAULT "0" COMMENT "商详页uv",
  `sku_cart_num` int(11) REPLACE DEFAULT "0" COMMENT "加购sku件数",
  `sku_order_num` int(11) REPLACE DEFAULT "0" COMMENT "下单sku件量",
  `sku_paid_num` int(11) REPLACE DEFAULT "0" COMMENT "支付sku件量",
  `session_viewproduct_count` int(11) REPLACE DEFAULT "0" COMMENT "商详session总数",
  `session_viewproduct_out_count` int(11) REPLACE DEFAULT "0" COMMENT "商详session跳出数",
  `count` tinyint(4) REPLACE DEFAULT "1" COMMENT "统计1"
) ENGINE=OLAP
AGGREGATE KEY(`datetime`, `website_id`, `platform_id`, `date`, `hourly_grain`)
PARTITION BY RANGE(`datetime`)
(PARTITION y2016 VALUES LESS THAN ("2017010100"),
PARTITION y2017 VALUES LESS THAN ("2018010100"),
PARTITION y2018 VALUES LESS THAN ("2019010100"),
PARTITION y2019 VALUES LESS THAN ("2020010100"))
DISTRIBUTED BY HASH(`date`, `website_id`) BUCKETS 6
PROPERTIES (
"storage_type" = "COLUMN"
);

CREATE TABLE `sales_flat_order` (
  `entity_id` int(11) COMMENT "__PRI__",
  `state` varchar(512) COMMENT "State",
  `status` varchar(512) COMMENT "Status",
  `coupon_code` varchar(512) COMMENT "Coupon Code",
  `protect_code` varchar(512) COMMENT "Protect Code",
  `shipping_description` varchar(512) COMMENT "Shipping Description",
  `is_virtual` int(11) COMMENT "Is Virtual",
  `store_id` int(11) COMMENT "Store Id",
  `customer_id` int(11) COMMENT "Customer Id",
  `base_discount_amount` double COMMENT "Base Discount Amount",
  `base_discount_canceled` double COMMENT "Base Discount Canceled",
  `base_discount_invoiced` double COMMENT "Base Discount Invoiced",
  `base_discount_refunded` double COMMENT "Base Discount Refunded",
  `base_grand_total` double COMMENT "Base Grand Total",
  `base_shipping_amount` double COMMENT "Base Shipping Amount",
  `base_shipping_canceled` double COMMENT "Base Shipping Canceled",
  `base_shipping_invoiced` double COMMENT "Base Shipping Invoiced",
  `base_shipping_refunded` double COMMENT "Base Shipping Refunded",
  `base_shipping_tax_amount` double COMMENT "Base Shipping Tax Amount",
  `base_shipping_tax_refunded` double COMMENT "Base Shipping Tax Refunded",
  `base_subtotal` double COMMENT "Base Subtotal",
  `base_subtotal_canceled` double COMMENT "Base Subtotal Canceled",
  `base_subtotal_invoiced` double COMMENT "Base Subtotal Invoiced",
  `base_subtotal_refunded` double COMMENT "Base Subtotal Refunded",
  `base_tax_amount` double COMMENT "Base Tax Amount",
  `base_tax_canceled` double COMMENT "Base Tax Canceled",
  `base_tax_invoiced` double COMMENT "Base Tax Invoiced",
  `base_tax_refunded` double COMMENT "Base Tax Refunded",
  `base_to_global_rate` double COMMENT "Base To Global Rate",
  `base_to_order_rate` double COMMENT "Base To Order Rate",
  `base_total_canceled` double COMMENT "Base Total Canceled",
  `base_total_invoiced` double COMMENT "Base Total Invoiced",
  `base_total_invoiced_cost` double COMMENT "Base Total Invoiced Cost",
  `base_total_offline_refunded` double COMMENT "Base Total Offline Refunded",
  `base_total_online_refunded` double COMMENT "Base Total Online Refunded",
  `base_total_paid` double COMMENT "Base Total Paid",
  `base_total_qty_ordered` double COMMENT "Base Total Qty Ordered",
  `base_total_refunded` double COMMENT "Base Total Refunded",
  `discount_amount` double COMMENT "Discount Amount",
  `discount_canceled` double COMMENT "Discount Canceled",
  `discount_invoiced` double COMMENT "Discount Invoiced",
  `discount_refunded` double COMMENT "Discount Refunded",
  `grand_total` double COMMENT "Grand Total",
  `shipping_amount` double COMMENT "Shipping Amount",
  `shipping_canceled` double COMMENT "Shipping Canceled",
  `shipping_invoiced` double COMMENT "Shipping Invoiced",
  `shipping_refunded` double COMMENT "Shipping Refunded",
  `shipping_tax_amount` double COMMENT "Shipping Tax Amount",
  `shipping_tax_refunded` double COMMENT "Shipping Tax Refunded",
  `store_to_base_rate` double COMMENT "Store To Base Rate",
  `store_to_order_rate` double COMMENT "Store To Order Rate",
  `subtotal` double COMMENT "Subtotal",
  `subtotal_canceled` double COMMENT "Subtotal Canceled",
  `subtotal_invoiced` double COMMENT "Subtotal Invoiced",
  `subtotal_refunded` double COMMENT "Subtotal Refunded",
  `tax_amount` double COMMENT "Tax Amount",
  `tax_canceled` double COMMENT "Tax Canceled",
  `tax_invoiced` double COMMENT "Tax Invoiced",
  `tax_refunded` double COMMENT "Tax Refunded",
  `total_canceled` double COMMENT "Total Canceled",
  `total_invoiced` double COMMENT "Total Invoiced",
  `total_offline_refunded` double COMMENT "Total Offline Refunded",
  `total_online_refunded` double COMMENT "Total Online Refunded",
  `total_paid` double COMMENT "Total Paid",
  `total_qty_ordered` double COMMENT "Total Qty Ordered",
  `total_refunded` double COMMENT "Total Refunded",
  `can_ship_partially` int(11) COMMENT "Can Ship Partially",
  `can_ship_partially_item` int(11) COMMENT "Can Ship Partially Item",
  `customer_is_guest` int(11) COMMENT "Customer Is Guest",
  `customer_note_notify` int(11) COMMENT "Customer Note Notify",
  `billing_address_id` int(11) COMMENT "Billing Address Id",
  `customer_group_id` int(11) COMMENT "Customer Group Id",
  `edit_increment` int(11) COMMENT "Edit Increment",
  `email_sent` int(11) COMMENT "Email Sent",
  `forced_shipment_with_invoice` int(11) COMMENT "Forced Do Shipment With Invoice",
  `payment_auth_expiration` int(11) COMMENT "Payment Authorization Expiration",
  `quote_address_id` int(11) COMMENT "Quote Address Id",
  `quote_id` int(11) COMMENT "Quote Id",
  `shipping_address_id` int(11) COMMENT "Shipping Address Id",
  `adjustment_negative` double COMMENT "Adjustment Negative",
  `adjustment_positive` double COMMENT "Adjustment Positive",
  `base_adjustment_negative` double COMMENT "Base Adjustment Negative",
  `base_adjustment_positive` double COMMENT "Base Adjustment Positive",
  `base_shipping_discount_amount` double COMMENT "Base Shipping Discount Amount",
  `base_subtotal_incl_tax` double COMMENT "Base Subtotal Incl Tax",
  `base_total_due` double COMMENT "Base Total Due",
  `payment_authorization_amount` double COMMENT "Payment Authorization Amount",
  `shipping_discount_amount` double COMMENT "Shipping Discount Amount",
  `subtotal_incl_tax` double COMMENT "Subtotal Incl Tax",
  `total_due` double COMMENT "Total Due",
  `weight` double COMMENT "Weight",
  `customer_dob` varchar(512) COMMENT "Customer Dob",
  `increment_id` varchar(512) COMMENT "Increment Id",
  `applied_rule_ids` varchar(512) COMMENT "Applied Rule Ids",
  `base_currency_code` varchar(512) COMMENT "Base Currency Code",
  `customer_email` varchar(512) COMMENT "Customer Email",
  `customer_firstname` varchar(512) COMMENT "Customer Firstname",
  `customer_lastname` varchar(512) COMMENT "Customer Lastname",
  `customer_middlename` varchar(512) COMMENT "Customer Middlename",
  `customer_prefix` varchar(512) COMMENT "Customer Prefix",
  `customer_suffix` varchar(512) COMMENT "Customer Suffix",
  `customer_taxvat` varchar(512) COMMENT "Customer Taxvat",
  `discount_description` varchar(512) COMMENT "Discount Description",
  `ext_customer_id` varchar(512) COMMENT "Ext Customer Id",
  `ext_order_id` varchar(512) COMMENT "Ext Order Id",
  `global_currency_code` varchar(512) COMMENT "Global Currency Code",
  `hold_before_state` varchar(512) COMMENT "Hold Before State",
  `hold_before_status` varchar(512) COMMENT "Hold Before Status",
  `order_currency_code` varchar(512) COMMENT "Order Currency Code",
  `original_increment_id` varchar(512) COMMENT "Original Increment Id",
  `relation_child_id` varchar(512) COMMENT "Relation Child Id",
  `relation_child_real_id` varchar(512) COMMENT "Relation Child Real Id",
  `relation_parent_id` varchar(512) COMMENT "Relation Parent Id",
  `relation_parent_real_id` varchar(512) COMMENT "Relation Parent Real Id",
  `remote_ip` varchar(512) COMMENT "Remote Ip",
  `shipping_method` varchar(512) COMMENT "Shipping Method",
  `store_currency_code` varchar(512) COMMENT "Store Currency Code",
  `store_name` varchar(512) COMMENT "Store Name",
  `x_forwarded_for` varchar(512) COMMENT "X Forwarded For",
  `customer_note` varchar(512) COMMENT "Customer Note",
  `created_at` varchar(512) COMMENT "Created At",
  `updated_at` varchar(512) COMMENT "Updated At",
  `total_item_count` int(11) COMMENT "Total Item Count",
  `customer_gender` int(11) COMMENT "Customer Gender",
  `hidden_tax_amount` double COMMENT "Hidden Tax Amount",
  `base_hidden_tax_amount` double COMMENT "Base Hidden Tax Amount",
  `shipping_hidden_tax_amount` double COMMENT "Shipping Hidden Tax Amount",
  `base_shipping_hidden_tax_amnt` double COMMENT "Base Shipping Hidden Tax Amount",
  `hidden_tax_invoiced` double COMMENT "Hidden Tax Invoiced",
  `base_hidden_tax_invoiced` double COMMENT "Base Hidden Tax Invoiced",
  `hidden_tax_refunded` double COMMENT "Hidden Tax Refunded",
  `base_hidden_tax_refunded` double COMMENT "Base Hidden Tax Refunded",
  `shipping_incl_tax` double COMMENT "Shipping Incl Tax",
  `base_shipping_incl_tax` double COMMENT "Base Shipping Incl Tax",
  `coupon_rule_name` varchar(512) COMMENT "Coupon Sales Rule Name",
  `paypal_ipn_customer_notified` int(11) COMMENT "Paypal Ipn Customer Notified",
  `gift_message_id` int(11) COMMENT "Gift Message Id",
  `onestepcheckout_customercomment` varchar(512) COMMENT "",
  `onestepcheckout_customerfeedback` varchar(512) COMMENT "",
  `pre_shipping_type` varchar(512) COMMENT "Pre Shipping Type",
  `shipping_type` varchar(512) COMMENT "",
  `package_gross_weight` double COMMENT "Package Gross Weight",
  `package_width` double COMMENT "Package Width",
  `package_height` double COMMENT "Package Height",
  `package_length` double COMMENT "Package Length",
  `shipment_info` varchar(512) COMMENT "Shipment Info",
  `partner_shipping_number` varchar(512) COMMENT "",
  `county` varchar(512) COMMENT "County",
  `stock_id` varchar(512) COMMENT "",
  `identity_status` varchar(512) COMMENT "",
  `beforehand_stock_id` varchar(512) COMMENT "Beforehand Stock Id",
  `parent_id` int(11) COMMENT "Parent Id",
  `is_parent` int(11) COMMENT "",
  `paid_at` varchar(512) COMMENT "",
  `ltcookie` varchar(512) COMMENT "",
  `order_source` varchar(512) COMMENT "",
  `logistics_status` varchar(512) COMMENT "",
  `original_grand_total` double COMMENT "",
  `original_currency_code` varchar(512) COMMENT "",
  `original_exchange_rate` double COMMENT "",
  `original_symbol` varchar(512) COMMENT "",
  `f51bi_cookie` varchar(512) COMMENT "",
  `promotion_source` varchar(512) COMMENT "",
  `is_send_identify` int(11) COMMENT "",
  `is_send_order` int(11) COMMENT "",
  `htc_send_status` int(11) COMMENT "",
  `supplier_product` double COMMENT "",
  `supplier_shipping` double COMMENT "",
  `azoya_product` double COMMENT ",
  `azoya_shipping` double COMMENT "",
  `is_export` varchar(512) COMMENT "",
  `itag` varchar(512) COMMENT "",
  `wtag` varchar(512) COMMENT "",
  `real_azoya_product` double COMMENT "",
  `real_azoya_shipping` double COMMENT "",
  `is_crontab` int(11) COMMENT "",
  `level` int(11) COMMENT "",
  `total_fee` double COMMENT "",
  `payment_currency` varchar(512) COMMENT "",
  `downloaded` varchar(512) COMMENT "",
  `supplier_order_no` varchar(512) COMMENT "",
  `product_discount_amount` double COMMENT "",
  `check_status` int(11) COMMENT "",
  `points_discount_amount` double COMMENT "",
  `order_type` int(11) COMMENT "",
  `is_new_promotion` int(11) COMMENT "",
  `comment_finish` int(11) COMMENT "",
  `share_order_status` varchar(512) COMMENT "",
  `is_sync` int(11) COMMENT "",
  `ftp_status` int(11) COMMENT "",
  `order_platform` int(11) COMMENT "",
  `sender_name` varchar(512) COMMENT "",
  `package_type` varchar(512) COMMENT "",
  `three_part_order_number` varchar(512) COMMENT "",
  `third_part_discount_amount` double COMMENT "",
  `seller_discount_amount` double COMMENT "",
  `payment_discount_amount` double COMMENT "",
  `completed_at` varchar(512) COMMENT "",
  `is_bonded` int(11) COMMENT "",
  `applied_rule_name` varchar(512) COMMENT "",
  `is_deleted___` int(11) COMMENT "",
  `timestamp___` largeint(40) COMMENT ""
) ENGINE=OLAP
UNIQUE KEY(`entity_id`)
DISTRIBUTED BY HASH(`entity_id`) BUCKETS 6
PROPERTIES (
"storage_type" = "COLUMN"
);
CREATE TABLE `sales_flat_order_item` (
  `item_id` int(11) COMMENT "__PRI__",
  `order_id` int(11) COMMENT "Order Id",
  `parent_item_id` int(11) COMMENT "Parent Item Id",
  `quote_item_id` int(11) COMMENT "Quote Item Id",
  `store_id` int(11) COMMENT "Store Id",
  `created_at` varchar(512) COMMENT "Created At",
  `updated_at` varchar(512) COMMENT "Updated At",
  `product_id` int(11) COMMENT "Product Id",
  `product_type` varchar(512) COMMENT "Product Type",
  `product_options` varchar(512) COMMENT "Product Options",
  `weight` double COMMENT "Weight",
  `is_virtual` int(11) COMMENT "Is Virtual",
  `sku` varchar(512) COMMENT "Sku",
  `name` varchar(512) COMMENT "Name",
  `description` varchar(512) COMMENT "Description",
  `applied_rule_ids` varchar(512) COMMENT "Applied Rule Ids",
  `additional_data` varchar(512) COMMENT "Additional Data",
  `free_shipping` int(11) COMMENT "Free Shipping",
  `is_qty_decimal` int(11) COMMENT "Is Qty Decimal",
  `no_discount` int(11) COMMENT "No Discount",
  `qty_backordered` double COMMENT "Qty Backordered",
  `qty_canceled` double COMMENT "Qty Canceled",
  `qty_invoiced` double COMMENT "Qty Invoiced",
  `qty_ordered` double COMMENT "Qty Ordered",
  `qty_refunded` double COMMENT "Qty Refunded",
  `qty_shipped` double COMMENT "Qty Shipped",
  `base_cost` double COMMENT "Base Cost",
  `price` double COMMENT "Price",
  `base_price` double COMMENT "Base Price",
  `original_price` double COMMENT "Original Price",
  `base_original_price` double COMMENT "Base Original Price",
  `tax_percent` double COMMENT "Tax Percent",
  `tax_amount` double COMMENT "Tax Amount",
  `base_tax_amount` double COMMENT "Base Tax Amount",
  `tax_invoiced` double COMMENT "Tax Invoiced",
  `base_tax_invoiced` double COMMENT "Base Tax Invoiced",
  `discount_percent` double COMMENT "Discount Percent",
  `discount_amount` double COMMENT "Discount Amount",
  `base_discount_amount` double COMMENT "Base Discount Amount",
  `discount_invoiced` double COMMENT "Discount Invoiced",
  `base_discount_invoiced` double COMMENT "Base Discount Invoiced",
  `amount_refunded` double COMMENT "Amount Refunded",
  `base_amount_refunded` double COMMENT "Base Amount Refunded",
  `row_total` double COMMENT "Row Total",
  `base_row_total` double COMMENT "Base Row Total",
  `row_invoiced` double COMMENT "Row Invoiced",
  `base_row_invoiced` double COMMENT "Base Row Invoiced",
  `row_weight` double COMMENT "Row Weight",
  `base_tax_before_discount` double COMMENT "Base Tax Before Discount",
  `tax_before_discount` double COMMENT "Tax Before Discount",
  `ext_order_item_id` varchar(512) COMMENT "Ext Order Item Id",
  `locked_do_invoice` int(11) COMMENT "Locked Do Invoice",
  `locked_do_ship` int(11) COMMENT "Locked Do Ship",
  `price_incl_tax` double COMMENT "Price Incl Tax",
  `base_price_incl_tax` double COMMENT "Base Price Incl Tax",
  `row_total_incl_tax` double COMMENT "Row Total Incl Tax",
  `base_row_total_incl_tax` double COMMENT "Base Row Total Incl Tax",
  `hidden_tax_amount` double COMMENT "Hidden Tax Amount",
  `base_hidden_tax_amount` double COMMENT "Base Hidden Tax Amount",
  `hidden_tax_invoiced` double COMMENT "Hidden Tax Invoiced",
  `base_hidden_tax_invoiced` double COMMENT "Base Hidden Tax Invoiced",
  `hidden_tax_refunded` double COMMENT "Hidden Tax Refunded",
  `base_hidden_tax_refunded` double COMMENT "Base Hidden Tax Refunded",
  `is_nominal` int(11) COMMENT "Is Nominal",
  `tax_canceled` double COMMENT "Tax Canceled",
  `hidden_tax_canceled` double COMMENT "Hidden Tax Canceled",
  `tax_refunded` double COMMENT "Tax Refunded",
  `base_tax_refunded` double COMMENT "Base Tax Refunded",
  `discount_refunded` double COMMENT "Discount Refunded",
  `base_discount_refunded` double COMMENT "Base Discount Refunded",
  `gift_message_id` int(11) COMMENT "Gift Message Id",
  `gift_message_available` int(11) COMMENT "Gift Message Available",
  `base_weee_tax_applied_amount` double COMMENT "Base Weee Tax Applied Amount",
  `base_weee_tax_applied_row_amnt` double COMMENT "Base Weee Tax Applied Row Amnt",
  `weee_tax_applied_amount` double COMMENT "Weee Tax Applied Amount",
  `weee_tax_applied_row_amount` double COMMENT "Weee Tax Applied Row Amount",
  `weee_tax_applied` varchar(512) COMMENT "Weee Tax Applied",
  `weee_tax_disposition` double COMMENT "Weee Tax Disposition",
  `weee_tax_row_disposition` double COMMENT "Weee Tax Row Disposition",
  `base_weee_tax_disposition` double COMMENT "Base Weee Tax Disposition",
  `base_weee_tax_row_disposition` double COMMENT "Base Weee Tax Row Disposition",
  `split_order` varchar(512) COMMENT "Split Order",
  `original_origin_price` double COMMENT "",
  `original_sales_price` double COMMENT "",
  `supplier_product` double COMMENT "供应商承受的折扣价格",
  `supplier_shipping` double COMMENT "供应商承受的运费价格",
  `azoya_product` double COMMENT "折扣价格",
  `azoya_shipping` double COMMENT "运费价格",
  `real_azoya_product` double COMMENT "真实折扣价格",
  `real_azoya_shipping` double COMMENT "真实运费价格",
  `order_group` varchar(512) COMMENT "Order Group",
  `shipping_discount_amount` double COMMENT "Shipping Discount Amount",
  `supplier_price` double COMMENT "",
  `express_tax_rate` double COMMENT "商品税率",
  `postal_tax_rate` double COMMENT "商品税率",
  `shipping_amount` double COMMENT "运费",
  `is_x_for_y` int(11) COMMENT "",
  `x_for_y_qty` int(11) COMMENT "",
  `offer_id` varchar(512) COMMENT "",
  `finance_price` double COMMENT "",
  `free_samples` int(11) COMMENT "",
  `points_spent` double COMMENT "",
  `supplier_pay_percent` varchar(512) COMMENT "",
  `supplier_pay_max` varchar(512) COMMENT "",
  `rule_details` varchar(512) COMMENT "",
  `supplier_product_id` varchar(512) COMMENT "",
  `is_comment` int(11) COMMENT "",
  `secondary_name` varchar(512) COMMENT "",
  `supplier_sku` varchar(512) COMMENT "",
  `hs_code` varchar(512) COMMENT "",
  `barcode` varchar(512) COMMENT "",
  `bsc_numbers` varchar(512) COMMENT "",
  `vat` double COMMENT "",
  `oos` int(11) COMMENT "",
  `third_part_discount_amount` double COMMENT "",
  `seller_discount_amount` double COMMENT "",
  `payment_discount_amount` double COMMENT "",
  `is_deleted___` int(11) COMMENT "",
  `timestamp___` largeint(40) COMMENT ""
) ENGINE=OLAP
UNIQUE KEY(`item_id`)
DISTRIBUTED BY HASH(`item_id`) BUCKETS 6
PROPERTIES (
"storage_type" = "COLUMN"
);
CREATE TABLE `currency_exchange_rate` (
  `date` int(11) NOT NULL COMMENT "年月日",
  `currency_code` varchar(10) NOT NULL COMMENT "币种",
  `rate` decimal(12, 8) REPLACE DEFAULT "0.0" COMMENT "汇率",
  `count` tinyint(4) REPLACE DEFAULT "1" COMMENT "统计1"
) ENGINE=OLAP
AGGREGATE KEY(`date`, `currency_code`)
DISTRIBUTED BY HASH(`date`) BUCKETS 6
PROPERTIES (
"storage_type" = "COLUMN"
);

**Comment by aherain** [comment]
我也常遇到，查询的数据量过大，be挂了，扫描的节点过多，通过建物化表把大数据量表group by 小数据量表 只能是一个折中的办法

**Comment by chenhao7253886** [comment]
这个问题已经解决，稍后我们合到github上。

**Comment by kangkaisen** [comment]
@chenhao7253886  Hi, What's the root cause of this issue ? How do we solve it ?  What's the related commit for this issue?  Thanks.
