### ISSUE TITLE
请问如何从把mysql的数据导入到Palo

### ISSUE THREAD

**Issue by ws2823147532** [baidu/palo#217]
看到文档示例：`load方式`能将hdfs的数据导入Palo，`mini load方式`可以将本地的文件通过http的方式导入Palo；在建表的时候可以指定ENGINE=mysql，但是下面又说：`在 Palo 创建 mysql 表的目的是可以通过 Palo 访问 mysql 数据库。而 Palo 本身并不维护、存储任何 mysql 数据`。
请问如何将mysql的数据直接导入Palo，必须要先从mysql中dump出文本格式的数据，再通过mini load方式将数据导入Palo吗？有没有直接一点的方式呢？

**Comment by imay** [comment]
可以创建一个MySQL外部表，help create table里面有说明。
然后通过insert...select方式来完成导入Palo表

**Comment by ws2823147532** [comment]
好的，谢谢。我试一下这种方式。

**Comment by ws2823147532** [comment]
您好，按照您的方式测试，报如下问题:ERROR 5025 (HY000): fail to convert mysql value '1899-12-31 00:00:00' TO DATETIME。
但是满足文档中的DATETIME类型的数据范围啊。
`DATETIME数据类型：范围: ['1000-01-01 00:00:00', '9999-12-31 00:00:00']。默认的打印形式是’YYYY-MM-DD HH:MM:SS’。`

**Comment by ws2823147532** [comment]
@imay 如果，我把这个字段的值改成1900-01-01 00:00:00 就可以成功执行了。这是不是bug。。

**Comment by ws2823147532** [comment]
我注意到：如果我依照DATE类型的key设置了partition，那么第一个分区一直都是从1900-01-01开始的，是不是palo系统的日期类型的数据的范围是`['1900-01-01 00:00:00', '9999-12-31 00:00:00']`.而不是文档中说的`['1000-01-01 00:00:00', '9999-12-31 00:00:00']`

**Comment by imay** [comment]
@ws2823147532 引擎存储的date类型最小应该是1900-01-01开始

**Comment by ws2823147532** [comment]
谢谢
