### ISSUE TITLE
BE日志

### ISSUE THREAD

**Issue by ws2823147532** [baidu/palo#218]
您好，
问题一：
今天发现一个BE节点挂了，查看日志提示：**be.INFO**
`W0814 13:20:26.759162 22682 segment_reader.cpp:301] segment init cost too much time. [load_segment_time_us=262597 load_index_stream_time_us=62458]`

问题二：
然后重启了BE，再次查看日志：**be.WARNING**
`W0814 15:00:40.603531 21487 cgroups_mgr.cpp:69] Cgroups manager initialized failed, will not update local cgroups!`
而且，顺表也查看了其他的BE节点的**be.WARNING**，也都有一样的日志

不知道上述问题是什么原因导致的。

> 备注：由于资源问题，机器的版本是CentOS 6，不知道这个是不是和问题二有关系。

**Comment by imay** [comment]
问题一：
这个是说单词读取的时间超长，并不影响正确性
问题二：
这个不是问题，这个日志我们后面会删除掉

**Comment by ws2823147532** [comment]
@imay  谢谢
