### ISSUE TITLE
错误使用hll时会导致be节点挂掉

### ISSUE THREAD

**Issue by zhangxinyu1** [baidu/palo#22]
首先创建一个有hll hll_union列的表
然后用curl --location-trusted -uname:password -T data http://host/api/test_db/test/_load?label=load_1   提交导入数据请求【注意：这里是错误使用hll】
则处理这个请求的be就会挂掉，报出如下的错误
![image](https://user-images.githubusercontent.com/12528894/29393652-9f9f6440-8337-11e7-909c-583a08f0d575.png)

**Comment by chenhao7253886** [comment]
好的，这个我看一下。可能是异常没处理好。
