### ISSUE TITLE
想单机部署测试下，但遇到问题 Failed to find enough host in all backends. need: 3

### ISSUE THREAD

**Issue by SpeechlessMan** [baidu/palo#220]
创建表时报错，是需要3个BE实例？还是必须要在三个不同的物理机器上？

**Comment by imay** [comment]
建表的时候可以设定副本数为1.
比如
CREATE TABLE abc ( k1 BIGINT NULL) DISTRIBUTED BY HASH(k1) BUCKETS 1
PROPERTIES (
"replication_num" = "1"
);

**Comment by SpeechlessMan** [comment]
问题已解决，非常感谢！
