### ISSUE TITLE
创建集群报错

### ISSUE THREAD

**Issue by freedomme** [baidu/palo#221]
MySQL [(none)]> CREATE CLUSTER example_cluster PROPERTIES("instance_num"="1") IDENTIFIED BY 'superuser';
ERROR 5036 (HY000): Be is not enough

环境 centos7.2  docker 运行方式 镜像0.8版本

**Comment by imay** [comment]
可以更新到最新的版本，show backends看一下当前有多少backend

**Comment by freedomme** [comment]
@buchongyu 是启动两个集群，开发用。不过docker 还有不少异常，我看还是不用docker 方式，改用普通安装，没有那么的问题
