### ISSUE TITLE
数据实时导入palo

### ISSUE THREAD

**Issue by ws2823147532** [baidu/palo#222]
@imay 您好，最近提了一些问题，非常感谢您的回答。

我目前根据palo支持的两种导数据的方式对于数据实时导入只能提出如下的解决方案：

- 1、对于hdfs的文件，有分区字段，设置一个定时脚本使用pull load方案将数据导入
- 2、对于mysql中的数据，无分区字段，事先创建一个mysql的外部表，然后设置一个定时脚本执行insert into table ... select ... from 方式将mysql中的数据导入到palo中，每次定时脚本执行前先清空原来的palo表。

实际上，我认为第一种针对于hdfs的数据的导入方式还算合理，但是第二种针对于mysql中的数据的导入方式就不太合理了。

请问在使用Palo时对于需要实时增量加载数据的应用场景有没有好的解决方案。

**Comment by imay** [comment]
对于从MySQL定期导入增量数据到Palo中，可以使用工具从MySQL定期同步更新数据，然后使用mini load方式导入到Palo中。
Palo在1-2个月内就会发布流式导入版本，届时导入的时效性会有一定提升

**Comment by ws2823147532** [comment]
ok.非常感谢。期待流式版本的发布
