### ISSUE TITLE
Failed to find enough alive backends

### ISSUE THREAD

**Issue by zlcnju** [baidu/palo#23]
使用默认的三副本方式建表，提示存活节点不够。
MySQL [dbtest]> CREATE TABLE table1 (     siteid INT DEFAULT '10',     citycode SMALLINT,     username VARCHAR(32) DEFAULT '',     pv BIGINT SUM DEFAULT '0' ) AGGREGATE KEY(siteid, citycode, username) DISTRIBUTED BY HASH(siteid) BUCKETS 10 ;
ERROR 1050 (42S01): Failed to find enough alive backends. need: 3
MySQL [dbtest]> SHOW PROC '/backends';
+-----------------+-----------+---------------+----------+---------------+--------+----------+---------------------+---------------------+-------+----------------------+-----------------------+-----------+
| Cluster         | BackendId | IP            | HostName | HeartbeatPort | BePort | HttpPort | LastStartTime       | LastHeartbeat       | Alive | SystemDecommissioned | ClusterDecommissioned | TabletNum |
+-----------------+-----------+---------------+----------+---------------+--------+----------+---------------------+---------------------+-------+----------------------+-----------------------+-----------+
|                 | 10376     | 192.168.5.100 | FineBI1  | 10050         | 9060   | 10040    | 2017-08-17 11:00:44 | 2017-08-17 11:13:09 | true  | false                | false                 | 0         |
| example_cluster | 10001     | 192.168.5.105 | FineBI2  | 9050          | 9060   | 8040     | 2017-08-17 11:00:54 | 2017-08-17 11:13:09 | true  | false                | false                 | 37        |
| example_cluster | 10002     | 192.168.5.106 | FineBI3  | 9050          | 9060   | 8040     | 2017-08-17 11:00:59 | 2017-08-17 11:13:09 | true  | false                | false                 | 37        |
+-----------------+-----------+---------------+----------+---------------+--------+----------+---------------------+---------------------+-------+----------------------+-----------------------+-----------+
3 rows in set (0.00 sec)

**Comment by chenhao7253886** [comment]
你的cluster内只有两个be啊，所以你只能创建两副本。palo为了保证高可用在每一个host上只会放一个副本，所以你两个be在两台机器上最多创建两副本的表。

**Comment by chenhao7253886** [comment]
你可以扩容一个节点来创建三副本的，首先在另外一个机器上部署另外一个be，然后通过alter system add backend加进集群，然后通过alter cluster cluster_name properties("instance_num" = "3") 扩容cluster的节点到三个。

**Comment by zlcnju** [comment]
有三个be，上面有列出来，分别是在finebi1，finebi2，finebi3三台机器上，而且都是存活状态

**Comment by chenhao7253886** [comment]
需要加进你的cluster啊，上面给你说了方法了。show proc "/backends" 注意下cluster这一栏，你的cluster内有几个be，只有两个需要把另外一个再加进去执行alter cluster cluster_name properties("instance_num" = "3")即可
