### ISSUE TITLE
cluster decommission无法完成

### ISSUE THREAD

**Issue by zlcnju** [baidu/palo#24]
使用3个be建立cluster后，删除了一个be，然后重新添加这个be，这个时候cluster是不能把这个be恢复到其所在cluster里的。这个时候使用alter cluster cluster_name properties("instance_num" = "2")设置副本为2，这个cluster就一直在cluster decommission状态，无法完成副本减少

**Comment by chenhao7253886** [comment]
drop掉是从整个物理集群踢掉，再加入是不能进入原有的cluster的。

**Comment by chenhao7253886** [comment]
你大概等了多久decommission没有结束

**Comment by zlcnju** [comment]
二十多分钟

**Comment by chenhao7253886** [comment]
你设置的表是不是两副本。

**Comment by chenhao7253886** [comment]
fixed
