### ISSUE TITLE
suggest to fix license statement

### ISSUE THREAD

**Issue by 7c00** [baidu/palo#29]
The license statements at the header of many source code look like:

>// Licensed to the **Apache Software Foundation (ASF)** under one
// or more contributor license agreements. ... The **ASF** licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); ...

It seems to be borrowed from some project of ASF. While Palo is not (at least currently) donated to ASF, so it might be not proper to put such statements.

**Comment by imay** [comment]
Thanks for advise, we will fix it soon.
