### ISSUE TITLE
 居然是Java还是ant

### ISSUE THREAD

**Issue by luyee** [baidu/palo#4]
居然不是maven，也不是gradle!

**Comment by maruyue** [comment]
为什么选用 ant，而不是 maven 和 graddle？考虑如下：

    ant 更简单，maven 和 graddle 使用更复杂
    对于很多在内网使用我们产品的同学，使用 maven 和 graddle 去下载外面的 jar 包，尤其遇到一些 jar 包还在国外封禁网站的，更是困难重重。很多公司的内网，是不能随意有外网权限的。
    palo 内置了一些 jar 包，不需要大家去下载，大大节省了大家的下载时间，用起来更方便。

我们在选用一些技术时，做了自己的一些考虑，不是带来实际收益，我们一般不会考虑引入。这里还是追求简洁有效。
