### ISSUE TITLE
thirdparty编译失败

### ISSUE THREAD

**Issue by Giant1** [baidu/palo#48]
===== begin build boost_1_64_0
Building Boost.Build engine with toolset gcc... tools/build/src/engine/bin.linuxx86_64/b2
Detecting Python version... 2.7
Detecting Python root... /data/anaconda
Unicode/ICU support for Boost.Regex?... not found.
Backing up existing Boost.Build configuration in project-config.jam.2
Generating Boost.Build configuration in project-config.jam...

Bootstrapping is done. To build, run:

    ./b2

To adjust configuration, edit 'project-config.jam'.
Further information:

   - Command line help:
     ./b2 --help

   - Getting started guide:
     http://www.boost.org/more/getting_started/unix-variants.html

   - Boost.Build documentation:
     http://www.boost.org/build/doc/html/index.html

Performing configuration checks

    - 32-bit                   : no  (cached)
    - 64-bit                   : yes (cached)
    - arm                      : no  (cached)
    - mips1                    : no  (cached)
    - power                    : no  (cached)
    - sparc                    : no  (cached)
    - x86                      : yes (cached)
    - symlinks supported       : yes (cached)
    - C++11 mutex              : yes (cached)
    - lockfree boost::atomic_flag : yes (cached)
    - Boost.Config Feature Check: cxx11_auto_declarations : yes (cached)
    - Boost.Config Feature Check: cxx11_constexpr : yes (cached)
    - Boost.Config Feature Check: cxx11_defaulted_functions : yes (cached)
    - Boost.Config Feature Check: cxx11_final : yes (cached)
    - Boost.Config Feature Check: cxx11_hdr_mutex : yes (cached)
    - Boost.Config Feature Check: cxx11_hdr_tuple : yes (cached)
    - Boost.Config Feature Check: cxx11_lambdas : yes (cached)
    - Boost.Config Feature Check: cxx11_noexcept : yes (cached)
    - Boost.Config Feature Check: cxx11_nullptr : yes (cached)
    - Boost.Config Feature Check: cxx11_rvalue_references : yes (cached)
    - Boost.Config Feature Check: cxx11_template_aliases : yes (cached)
    - Boost.Config Feature Check: cxx11_thread_local : yes (cached)
    - Boost.Config Feature Check: cxx11_variadic_templates : yes (cached)
    - zlib                     : yes (cached)
    - bzip2                    : no  (cached)
    - iconv (libc)             : yes (cached)
    - icu                      : no  (cached)
    - icu (lib64)              : no  (cached)
    - native-atomic-int32-supported : yes (cached)
    - native-syslog-supported  : yes (cached)
    - pthread-supports-robust-mutexes : yes (cached)
    - compiler-supports-visibility : yes (cached)
    - compiler-supports-ssse3  : yes (cached)
    - compiler-supports-avx2   : yes (cached)
    - has_icu builds           : no  (cached)
    - gcc visibility           : yes (cached)
    - long double support      : yes (cached)
    - zlib                     : yes (cached)
    - bzip2                    : no  (cached)

Component configuration:

    - atomic                   : building
    - chrono                   : building
    - container                : building
    - context                  : building
    - coroutine                : building
    - coroutine2               : building
    - date_time                : building
    - exception                : building
    - fiber                    : building
    - filesystem               : building
    - graph                    : not building
    - graph_parallel           : not building
    - iostreams                : building
    - locale                   : building
    - log                      : building
    - math                     : building
    - metaparse                : building
    - mpi                      : not building
    - program_options          : building
    - python                   : not building
    - random                   : building
    - regex                    : building
    - serialization            : building
    - signals                  : building
    - system                   : building
    - test                     : building
    - thread                   : building
    - timer                    : building
    - type_erasure             : building
    - wave                     : building

libs/fiber/src/context.cpp: 在构造函数‘boost::fibers::context::context(boost::fibers::dispatcher_context_t, const boost::context::preallocated&, const default_stack&, boost::fibers::scheduler*)’中:
libs/fiber/src/context.cpp:236:14: 错误：调用重载的‘callcc(const std::allocator_arg_t&, const boost::context::preallocated&, const default_stack&, boost::fibers::context::context(boost::fibers::dispatcher_context_t, const boost::context::preallocated&, const default_stack&, boost::fibers::scheduler*)::__lambda5)’有歧义
             });
              ^
libs/fiber/src/context.cpp:236:14: 附注：备选是：
In file included from /data/palo/palo/thirdparty/..//thirdparty/installed/include/boost/fiber/context.hpp:28:0,
                 from libs/fiber/src/context.cpp:7:
/data/palo/palo/thirdparty/..//thirdparty/installed/include/boost/context/continuation.hpp:469:1: 附注：boost::context::continuation boost::context::callcc(std::allocator_arg_t, StackAlloc, Fn&&, Arg ...) [with StackAlloc = boost::context::preallocated; Fn = const boost::context::basic_fixedsize_stack<boost::context::stack_traits>&; Arg = {boost::fibers::context::context(boost::fibers::dispatcher_context_t, const boost::context::preallocated&, const default_stack&, boost::fibers::scheduler*)::__lambda5}]
 callcc( std::allocator_arg_t, StackAlloc salloc, Fn && fn, Arg ... arg) {
 ^
/data/palo/palo/thirdparty/..//thirdparty/installed/include/boost/context/continuation.hpp:483:1: 附注：boost::context::continuation boost::context::callcc(std::allocator_arg_t, boost::context::preallocated, StackAlloc, Fn&&, Arg ...) [with StackAlloc = boost::context::basic_fixedsize_stack<boost::context::stack_traits>; Fn = boost::fibers::context::context(boost::fibers::dispatcher_context_t, const boost::context::preallocated&, const default_stack&, boost::fibers::scheduler*)::__lambda5; Arg = {}]
 callcc( std::allocator_arg_t, preallocated palloc, StackAlloc salloc, Fn && fn, Arg ... arg) {
 ^
/data/palo/palo/thirdparty/..//thirdparty/installed/include/boost/context/continuation.hpp:514:1: 附注：boost::context::continuation boost::context::callcc(std::allocator_arg_t, boost::context::preallocated, StackAlloc, Fn&&) [with StackAlloc = boost::context::basic_fixedsize_stack<boost::context::stack_traits>; Fn = boost::fibers::context::context(boost::fibers::dispatcher_context_t, const boost::context::preallocated&, const default_stack&, boost::fibers::scheduler*)::__lambda5]
 callcc( std::allocator_arg_t, preallocated palloc, StackAlloc salloc, Fn && fn) {
 ^
/data/palo/palo/thirdparty/..//thirdparty/installed/include/boost/context/continuation.hpp:457:1: 附注：boost::context::continuation boost::context::callcc(Fn&&, Arg ...) [with Fn = const std::allocator_arg_t&; Arg = {boost::context::preallocated, boost::context::basic_fixedsize_stack<boost::context::stack_traits>, boost::fibers::context::context(boost::fibers::dispatcher_context_t, const boost::context::preallocated&, const default_stack&, boost::fibers::scheduler*)::__lambda5}; <模板形参-1-3> = void]
 callcc( Fn && fn, Arg ... arg) {
 ^
...skipped <pbin.v2/libs/fiber/build/gcc-4.8.5/release/link-static/threading-multi>libboost_fiber.a(clean) for lack of <pbin.v2/libs/fiber/build/gcc-4.8.5/release/link-static/threading-multi>context.o...
...skipped <pbin.v2/libs/fiber/build/gcc-4.8.5/release/link-static/threading-multi>libboost_fiber.a for lack of <pbin.v2/libs/fiber/build/gcc-4.8.5/release/link-static/threading-multi>context.o...
...skipped <p/data/palo/palo/thirdparty/installed/lib>libboost_fiber.a for lack of <pbin.v2/libs/fiber/build/gcc-4.8.5/release/link-static/threading-multi>libboost_fiber.a...
libs/fiber/src/context.cpp: 在构造函数‘boost::fibers::context::context(boost::fibers::dispatcher_context_t, const boost::context::preallocated&, const default_stack&, boost::fibers::scheduler*)’中:
libs/fiber/src/context.cpp:236:14: 错误：调用重载的‘callcc(const std::allocator_arg_t&, const boost::context::preallocated&, const default_stack&, boost::fibers::context::context(boost::fibers::dispatcher_context_t, const boost::context::preallocated&, const default_stack&, boost::fibers::scheduler*)::__lambda5)’有歧义
             });
              ^
libs/fiber/src/context.cpp:236:14: 附注：备选是：
In file included from /data/palo/palo/thirdparty/..//thirdparty/installed/include/boost/fiber/context.hpp:28:0,
                 from libs/fiber/src/context.cpp:7:
/data/palo/palo/thirdparty/..//thirdparty/installed/include/boost/context/continuation.hpp:469:1: 附注：boost::context::continuation boost::context::callcc(std::allocator_arg_t, StackAlloc, Fn&&, Arg ...) [with StackAlloc = boost::context::preallocated; Fn = const boost::context::basic_fixedsize_stack<boost::context::stack_traits>&; Arg = {boost::fibers::context::context(boost::fibers::dispatcher_context_t, const boost::context::preallocated&, const default_stack&, boost::fibers::scheduler*)::__lambda5}]
 callcc( std::allocator_arg_t, StackAlloc salloc, Fn && fn, Arg ... arg) {
 ^
/data/palo/palo/thirdparty/..//thirdparty/installed/include/boost/context/continuation.hpp:483:1: 附注：boost::context::continuation boost::context::callcc(std::allocator_arg_t, boost::context::preallocated, StackAlloc, Fn&&, Arg ...) [with StackAlloc = boost::context::basic_fixedsize_stack<boost::context::stack_traits>; Fn = boost::fibers::context::context(boost::fibers::dispatcher_context_t, const boost::context::preallocated&, const default_stack&, boost::fibers::scheduler*)::__lambda5; Arg = {}]
 callcc( std::allocator_arg_t, preallocated palloc, StackAlloc salloc, Fn && fn, Arg ... arg) {
 ^
/data/palo/palo/thirdparty/..//thirdparty/installed/include/boost/context/continuation.hpp:514:1: 附注：boost::context::continuation boost::context::callcc(std::allocator_arg_t, boost::context::preallocated, StackAlloc, Fn&&) [with StackAlloc = boost::context::basic_fixedsize_stack<boost::context::stack_traits>; Fn = boost::fibers::context::context(boost::fibers::dispatcher_context_t, const boost::context::preallocated&, const default_stack&, boost::fibers::scheduler*)::__lambda5]
 callcc( std::allocator_arg_t, preallocated palloc, StackAlloc salloc, Fn && fn) {
 ^
/data/palo/palo/thirdparty/..//thirdparty/installed/include/boost/context/continuation.hpp:457:1: 附注：boost::context::continuation boost::context::callcc(Fn&&, Arg ...) [with Fn = const std::allocator_arg_t&; Arg = {boost::context::preallocated, boost::context::basic_fixedsize_stack<boost::context::stack_traits>, boost::fibers::context::context(boost::fibers::dispatcher_context_t, const boost::context::preallocated&, const default_stack&, boost::fibers::scheduler*)::__lambda5}; <模板形参-1-3> = void]
 callcc( Fn && fn, Arg ... arg) {
 ^
...skipped <pbin.v2/libs/fiber/build/gcc-4.8.5/release/threading-multi>libboost_fiber.so.1.64.0 for lack of <pbin.v2/libs/fiber/build/gcc-4.8.5/release/threading-multi>context.o...
...skipped <p/data/palo/palo/thirdparty/installed/lib>libboost_fiber.so.1.64.0 for lack of <pbin.v2/libs/fiber/build/gcc-4.8.5/release/threading-multi>libboost_fiber.so.1.64.0...
...skipped <p/data/palo/palo/thirdparty/installed/lib>libboost_fiber.so for lack of <p/data/palo/palo/thirdparty/installed/lib>libboost_fiber.so.1.64.0...
...failed updating 2 targets...

**Comment by Giant1** [comment]
thirdparty编译失败

**Comment by morningman** [comment]
请参阅 docs/admin_guide/install.md 中 "4.常见问题解决" 中 boost 编译相关问题的解决方案。

**Comment by Giant1** [comment]
您好，将boost_1_64_0打完patch后thirdparty编译成功，但是在编译be的时候出现了如下错误 。

[ 78%] Building CXX object src/olap/CMakeFiles/Olap.dir/column_file/column_reader.cpp.o
[ 78%] Building CXX object src/rpc/CMakeFiles/RPC.dir/poll_event.cpp.o
[ 78%] Building CXX object src/rpc/CMakeFiles/RPC.dir/protocol.cpp.o
[ 78%] Building CXX object src/rpc/CMakeFiles/RPC.dir/proxy_map.cpp.o
[ 78%] Building CXX object src/exec/CMakeFiles/Exec.dir/partitioned_hash_table.cc.o
[ 79%] Building CXX object src/rpc/CMakeFiles/RPC.dir/random.cpp.o
[ 79%] Building CXX object src/rpc/CMakeFiles/RPC.dir/reactor.cpp.o
[ 79%] Building CXX object src/olap/CMakeFiles/Olap.dir/column_file/column_writer.cpp.o
[ 80%] [ 80%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/datetime_value.cpp.o
Building CXX object src/rpc/CMakeFiles/RPC.dir/reactor_factory.cpp.o
[ 80%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/descriptors.cpp.o
[ 80%] Building CXX object src/olap/CMakeFiles/Olap.dir/column_file/compress.cpp.o
[ 80%] Building CXX object src/rpc/CMakeFiles/RPC.dir/reactor_runner.cpp.o
[ 80%] Building CXX object src/olap/CMakeFiles/Olap.dir/column_file/data_writer.cpp.o
[ 81%] Building CXX object src/rpc/CMakeFiles/RPC.dir/request_cache.cpp.o
[ 81%] Building CXX object src/rpc/CMakeFiles/RPC.dir/response_callback.cpp.o
[ 81%] Building CXX object src/exec/CMakeFiles/Exec.dir/partitioned_hash_table_ir.cc.o
[ 81%] Building CXX object src/exec/CMakeFiles/Exec.dir/partitioned_aggregation_node.cc.o
[ 81%] Building CXX object src/rpc/CMakeFiles/RPC.dir/util.cpp.o
Linking CXX static library libRPC.a
[ 81%] Built target RPC
[ 82%] Building CXX object src/exec/CMakeFiles/Exec.dir/partitioned_aggregation_node_ir.cc.o
[ 83%] Building CXX object src/olap/CMakeFiles/Olap.dir/column_file/file_stream.cpp.o
[ 83%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/exec_env.cpp.o
[ 83%] Building CXX object src/olap/CMakeFiles/Olap.dir/column_file/in_stream.cpp.o
Scanning dependencies of target PaloUdf
[ 83%] Building CXX object src/olap/CMakeFiles/Olap.dir/column_file/out_stream.cpp.o
[ 83%] Building CXX object src/udf/CMakeFiles/PaloUdf.dir/udf.cpp.o
[ 83%] Building CXX object src/udf/CMakeFiles/PaloUdf.dir/udf_ir.cpp.o
Linking CXX static library libPaloUdf.a
[ 83%] Built target PaloUdf
[ 83%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/lib_cache.cpp.o
[ 83%] Building CXX object src/olap/CMakeFiles/Olap.dir/column_file/run_length_byte_reader.cpp.o
[ 83%] Building CXX object src/exec/CMakeFiles/Exec.dir/local_file_writer.cpp.o
[ 83%] Building CXX object src/exec/CMakeFiles/Exec.dir/broker_writer.cpp.o
[ 84%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/mem_pool.cpp.o
[ 85%] Building CXX object src/olap/CMakeFiles/Olap.dir/column_file/run_length_byte_writer.cpp.o
[ 85%] Building CXX object src/olap/CMakeFiles/Olap.dir/column_file/run_length_integer_reader.cpp.o
[ 85%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/plan_fragment_executor.cpp.o
[ 85%] Building CXX object src/olap/CMakeFiles/Olap.dir/column_file/run_length_integer_writer.cpp.o
[ 85%] Building CXX object src/olap/CMakeFiles/Olap.dir/column_file/segment_reader.cpp.o
[ 86%] Building CXX object src/olap/CMakeFiles/Olap.dir/column_file/segment_writer.cpp.o
Linking CXX static library libExec.a
[ 86%] Built target Exec
[ 86%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/primitive_type.cpp.o
[ 86%] Building CXX object src/olap/CMakeFiles/Olap.dir/column_file/serialize.cpp.o
[ 86%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/pull_load_task_mgr.cpp.o
/data/palo/palo/be/src/runtime/pull_load_task_mgr.cpp: 在成员函数‘palo::Status palo::PullLoadTaskCtx::add_sub_task_info(const palo::TPullLoadSubTaskInfo&, bool*)’中:
/data/palo/palo/be/src/runtime/pull_load_task_mgr.cpp:96:16: 警告：未使用的变量‘it’ [-Wunused-variable]
     for (auto& it : sub_task_info.counters) {
                ^
[ 87%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/raw_value.cpp.o
[ 87%] Building CXX object src/olap/CMakeFiles/Olap.dir/column_file/stream_index_common.cpp.o
[ 87%] Building CXX object src/olap/CMakeFiles/Olap.dir/column_file/stream_index_reader.cpp.o
[ 87%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/raw_value_ir.cpp.o
[ 88%] Building CXX object src/olap/CMakeFiles/Olap.dir/column_file/stream_index_writer.cpp.o
Scanning dependencies of target compile_to_ir_sse
[ 88%] Generating ../../../../gensrc/build/palo_ir/palo_sse.bc
[ 88%] Building CXX object src/olap/CMakeFiles/Olap.dir/column_file/stream_name.cpp.o
[ 88%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/result_sink.cpp.o
[ 88%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/result_writer.cpp.o
Linking CXX static library libOlap.a
[ 88%] Built target Olap
Scanning dependencies of target compile_to_ir_no_sse
[ 88%] Generating ../../../../gensrc/build/palo_ir/palo_no_sse.bc
[ 89%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/result_buffer_mgr.cpp.o
[ 89%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/row_batch.cpp.o
[ 89%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/runtime_state.cpp.o
/data/palo/palo/be/src/runtime/row_batch.cpp: 在构造函数‘palo::RowBatch::RowBatch(const palo::RowDescriptor&, const palo::TRowBatch&, palo::MemTracker*)’中:
/data/palo/palo/be/src/runtime/row_batch.cpp:131:10: 警告：未使用的变量‘has_string_slots’ [-Wunused-variable]
     bool has_string_slots = _row_desc.has_varlen_slots();
          ^
/data/palo/palo/be/src/runtime/row_batch.cpp:138:12: 警告：variable ‘last_converted’ set but not used [-Wunused-but-set-variable]
     Tuple* last_converted = NULL;
            ^
[ 89%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/string_value.cpp.o
[ 90%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/thread_resource_mgr.cpp.o
[ 90%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/decimal_value.cpp.o
[ 90%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/large_int_value.cpp.o
[ 90%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/tuple.cpp.o
[ 91%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/tuple_row.cpp.o
[ 91%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/vectorized_row_batch.cpp.o
[ 91%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/dpp_writer.cpp.o
[ 91%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/qsorter.cpp.o
[ 92%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/fragment_mgr.cpp.o
[ 92%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/dpp_sink_internal.cpp.o
[ 92%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/data_spliter.cpp.o
[ 92%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/dpp_sink.cpp.o
[ 93%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/etl_job_mgr.cpp.o
[ 93%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/load_path_mgr.cpp.o
[ 93%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/mysql_table_writer.cpp.o
[ 93%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/mysql_table_sink.cpp.o
[ 94%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/types.cpp.o
[ 94%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/tmp_file_mgr.cc.o
[ 94%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/disk_io_mgr.cc.o
[ 94%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/disk_io_mgr_reader_context.cc.o
[ 95%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/disk_io_mgr_scan_range.cc.o
[ 95%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/buffered_block_mgr2.cc.o
[ 95%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/test_env.cc.o
[ 95%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/mem_tracker.cpp.o
[ 96%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/spill_sorter.cc.o
/data/palo/palo/be/src/runtime/mem_tracker.cpp: 在静态成员函数‘static palo::MemTracker* palo::MemTracker::CreateQueryMemTracker(const palo::TUniqueId&, const palo::TQueryOptions&, const string&, palo::ObjectPool*)’中:
/data/palo/palo/be/src/runtime/mem_tracker.cpp:177:17: 警告：未使用的变量‘pool_tracker’ [-Wunused-variable]
     MemTracker* pool_tracker =
                 ^
/data/palo/palo/be/src/runtime/mem_tracker.cpp:180:1: 警告：在有返回值的函数中未发现 return 语句 [-Wreturn-type]
 }
 ^
[ 96%] Built target compile_to_ir_sse
[ 96%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/sorted_run_merger.cc.o
[ 96%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/data_stream_recvr.cc.o
[ 96%] Built target compile_to_ir_no_sse
[ 96%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/buffered_tuple_stream2.cc.o
[ 97%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/buffered_tuple_stream2_ir.cc.o
[ 97%] Building CXX object src/runtime/CMakeFiles/Runtime.dir/export_sink.cpp.o
[ 97%] Generating ../../../../gensrc/build/palo_ir/palo_sse_ir.cpp
[ 98%] Generating ../../../../gensrc/build/palo_ir/palo_no_sse_ir.cpp
Scanning dependencies of target CodeGen
[ 98%] Building CXX object src/codegen/CMakeFiles/CodeGen.dir/codegen_anyval.cpp.o
[ 99%] Building CXX object src/codegen/CMakeFiles/CodeGen.dir/llvm_codegen.cpp.o
[ 99%] Building CXX object src/codegen/CMakeFiles/CodeGen.dir/subexpr_elimination.cpp.o
[ 99%] Building CXX object src/codegen/CMakeFiles/CodeGen.dir/__/__/__/gensrc/build/palo_ir/palo_sse_ir.cpp.o
Linking CXX static library libRuntime.a
[ 99%] Built target Runtime
[ 99%] Building CXX object src/codegen/CMakeFiles/CodeGen.dir/__/__/__/gensrc/build/palo_ir/palo_no_sse_ir.cpp.o
Linking CXX static library libCodeGen.a
[ 99%] Built target CodeGen
Scanning dependencies of target palo_be
[100%] Building CXX object src/service/CMakeFiles/palo_be.dir/palo_main.cpp.o
Linking CXX executable palo_be
../../../../thirdparty/installed//lib/libunwind.a(elf64.o)：在函数‘xz_uncompressed_size’中：
elf64.c:(.text+0x4eb)：对‘lzma_stream_footer_decode’未定义的引用
elf64.c:(.text+0x550)：对‘lzma_index_buffer_decode’未定义的引用
elf64.c:(.text+0x567)：对‘lzma_index_size’未定义的引用
elf64.c:(.text+0x57c)：对‘lzma_index_uncompressed_size’未定义的引用
elf64.c:(.text+0x591)：对‘lzma_index_end’未定义的引用
../../../../thirdparty/installed//lib/libunwind.a(elf64.o)：在函数‘_Uelf64_extract_minidebuginfo’中：
elf64.c:(.text+0x7b7)：对‘lzma_stream_buffer_decode’未定义的引用
collect2: 错误：ld 返回 1
make[2]: *** [src/service/palo_be] 错误 1
make[1]: *** [src/service/CMakeFiles/palo_be.dir/all] 错误 2
make: *** [all] 错误 2
