### ISSUE TITLE
建议palo的同学给预编译版本的名称palo-0.8.0_ubuntu16.04加上tar.gz的后缀

### ISSUE THREAD

**Issue by buchongyu** [baidu/palo#49]
![image](https://user-images.githubusercontent.com/8272958/29746823-1fac3c74-8b19-11e7-99c4-9397e4003740.png)

建议：palo同学在wiki（https://github.com/baidu/palo/blob/master/docs/admin_guide/install.md）中给palo-0.8.0_ubuntu16.04的结尾加上.tar.gz标识，我第一眼看到，还以为是个ios文件呢。

**Comment by cyongli** [comment]
OK，我们下次提交的时候，给文件名加上后缀。
