### ISSUE TITLE
"Apache" Impala vs. "Cloudera" Impala

### ISSUE THREAD

**Issue by jbapple-cloudera** [baidu/palo#58]
Cloudera no longer owns the TM for Impala - it is now an Apache Software Foundation project. I noticed it is still called "Cloudera" Impala in the README; it might be in other documentation in this repo as well.

**Comment by cyongli** [comment]
because we forked impala previous version, some description are not changed。I will change "Cloudera Impala" to "Apache Impala" in next pull request。
