### ISSUE TITLE
load label 中的hadoop

### ISSUE THREAD

**Issue by marcohsy5** [baidu/palo#61]
Cannot run program "/home/worker/palo-0.8.0_20170822_centos7.1_gcc485/fe/lib/hadoop-client/hadoop/bin/hadoop": error=2, No such file or directory

不是很懂这个hadoop是怎么来的，还是说得依赖自己的hadoop集群

**Comment by cyongli** [comment]
palo在公司内部是走hadoop导入的时候是集成了hadoop-client，这个目录是给内部用户导入用的。
外部开源用户使用的时候如果需要导入数据，可以通过apache hdfs broker
