### ISSUE TITLE
http小批量导入报错curl: Can't open 'table1_data'

### ISSUE THREAD

**Issue by Knuth1989** [baidu/palo#73]
[root@slave2 log]# curl --location-trusted -u root@example_cluster:root -T "table1_data" http://192.168.1.32:8030/api/example_db/table1/_load?label=table1_20170709
curl: Can't open 'table1_data'!
curl: try 'curl --help' or 'curl --manual' for more information

**Comment by imay** [comment]
这个应该是说没有找到本地文件table1_data，请确认是否有这个文件存在

**Comment by Knuth1989** [comment]
本地是有这个文件的 ，并且昨天我还是可以成功导入数据的

**Comment by imay** [comment]
这个错误是curl爆出来的，应该跟Palo关系不大。可以使用-v选项来查看curl具体的执行。还有就是下次贴命令行的时候注意不要贴用户名，密码敏感信息

**Comment by Knuth1989** [comment]
好的 ，谢谢您！
