### ISSUE TITLE
创建表时，报错：ERROR 1046 (3D000): Failed to create partition[table1]. Timeout

### ISSUE THREAD

**Issue by Knuth1989** [baidu/palo#80]
创建表时，报错：ERROR 1046 (3D000): Failed to create partition[table1]. Timeout
1）fe日志报错：
2017-09-07 17:35:30,628 INFO 101 [Database.checkQuota():239] database[example_cluster:example_db] data quota: left bytes: 1024.000 GB / total: 1024.000 GB
2017-09-07 17:35:40,671 WARN 101 [Catalog.createPartitionWithIndices():2779] Failed to create partition[table1]. Timeout. unfinished marks: 10000=10017, 10000=10019, 10000=10005, 10000=10021, 10000=10007, 10000=10023, 10000=10009, 10000=10011, 10000=10013, 10000=10015

**Comment by imay** [comment]
可以把对应BE的Log贴一下还有你的建表语句

**Comment by morningman** [comment]
unfinished marks: 10000=10017 ,其中 10000 是 backendId，可以通过  show proc "/backends"; 查看多赢的Backend 节点， 10017 是 tablet id，可以到10000这个backend上，查看下 be.INFO 日志中有没有关于 10017 这个 tablet 的错误信息。

**Comment by Knuth1989** [comment]
1）mysql> show proc "/backends";
*************************** 1. row ***************************
Cluster: example_cluster
BackendId: 10000
IP: 192.168.1.31
HostName: slave2
HeartbeatPort: 9050
BePort: 9060
HttpPort: 8040
LastStartTime: 2017-09-11 10:44:17
LastHeartbeat: 2017-09-11 11:01:47
Alive: true
SystemDecommissioned: false
ClusterDecommissioned: false
TabletNum: 40
1 row in set (0.01 sec)

2）be日志
W0911 10:59:53.233541  5449 utils.cpp:136] master client, get client from cache failed.host: 192.168.122.1, port: 9020, code: 7
W0911 10:59:53.233600  5449 task_worker_pool.cpp:276] finish task failed.result: 0
CREATE TABLE table1
(
    siteid INT DEFAULT '10',
    citycode SMALLINT,
    username VARCHAR(32) DEFAULT '',
    pv BIGINT SUM DEFAULT '0'
)
AGGREGATE KEY(siteid, citycode, username)
DISTRIBUTED BY HASH(siteid) BUCKETS 10
PROPERTIES("replication_num" = "1");
W0911 10:59:54.274317  5449 utils.cpp:136] master client, get client from cache failed.host: 192.168.122.1, port: 9020, code: 7
I0911 10:59:57.256597  5448 task_worker_pool.cpp:236] type: 0, signature: 10017 has been erased. queue size: 3
I0911 10:59:57.256640  5448 command_executor.cpp:245] begin to process create table. [tablet=10023, schema_hash=1421156361]
 
日志里一直报master client, get client from cache failed.host: 192.168.122.1，而我的fe节点是192.168.1.32

3）用8月16号预编译版本，可以成功建表，而且日志为
I0905 16:04:13.935012  5817 heartbeat_server.cpp:58] get heartbeat, host: 192.168.1.32, port: 9020, cluster id: 918677695，连接的是192.168.1.32 ，正常

**Comment by morningman** [comment]
"用8月16号预编译版本，可以成功建表" 是什么意思？你报错的这个是什么版本？

**Comment by Knuth1989** [comment]
报错的是我自己编译的版本

**Comment by morningman** [comment]
方便加下微信么？morningman-cmy

**Comment by Knuth1989** [comment]
感谢解决问题，解决方法：
1)ifconfig 看到
virbr0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 192.168.122.1  netmask 255.255.255.0  broadcast 192.168.122.255
2)日志里一直报master client, get client from cache failed.host: 192.168.122.1,将这个virbr0删除,重启fe即可
