### ISSUE TITLE
Centos6.x上编译be时遇到Error提示，请多多指教。

### ISSUE THREAD

**Issue by liuzx32** [baidu/palo#85]
openldap.c:(.text+0xc0f): undefined reference to `ldap_abandon_ext'
../../../../thirdparty/installed//lib/libcurl.a(libcurl_la-openldap.o): In function `ldap_do':
openldap.c:(.text+0xc6f): undefined reference to `ldap_url_parse'
openldap.c:(.text+0xd18): undefined reference to `ldap_search_ext'
openldap.c:(.text+0xd25): undefined reference to `ldap_free_urldesc'
openldap.c:(.text+0xd32): undefined reference to `ldap_err2string'
../../../../thirdparty/installed//lib/libcurl.a(libcurl_la-openldap.o): In function `ldap_setup_connection':
openldap.c:(.text+0xdeb): undefined reference to `ldap_url_parse'
openldap.c:(.text+0xe5a): undefined reference to `ldap_pvt_url_scheme2proto'
openldap.c:(.text+0xe67): undefined reference to `ldap_free_urldesc'
collect2: error: ld returned 1 exit status
make[2]: *** [src/service/palo_be] Error 1
make[1]: *** [src/service/CMakeFiles/palo_be.dir/all] Error 2
make: *** [all] Error 2

**Comment by liuzx32** [comment]
[  0%] Built target Udf
[  0%] Built target gen_ir_descriptions
[  9%] Built target Util
[ 22%] Built target Exec
[ 31%] Built target Exprs
[ 31%] Built target compile_to_ir_sse
[ 31%] Built target compile_to_ir_no_sse
[ 33%] Built target CodeGen
[ 35%] Built target Common
[ 48%] Built target PaloGen
[ 57%] Built target Gutil
[ 70%] Built target Olap
[ 72%] Built target Agent
[ 77%] Built target Webserver
[ 77%] Built target Service
[ 77%] Built target AES
[ 91%] Built target Runtime
[ 92%] Built target TestUtil
[ 99%] Built target RPC
Linking CXX executable palo_be
../../../../thirdparty/installed//lib/libcurl.a(libcurl_la-openldap.o): In function `ldap_disconnect':
openldap.c:(.text+0x52): undefined reference to `ldap_unbind_ext'
../../../../thirdparty/installed//lib/libcurl.a(libcurl_la-openldap.o): In function `ldap_connecting':
openldap.c:(.text+0xfe): undefined reference to `ldap_result'
openldap.c:(.text+0x138): undefined reference to `ldap_parse_result'
openldap.c:(.text+0x162): undefined reference to `ldap_get_option'
openldap.c:(.text+0x17c): undefined reference to `ldap_memfree'
openldap.c:(.text+0x19d): undefined reference to `ldap_set_option'
openldap.c:(.text+0x1ed): undefined reference to `ldap_sasl_bind'
openldap.c:(.text+0x21b): undefined reference to `ldap_memfree'
openldap.c:(.text+0x25e): undefined reference to `ldap_err2string'
openldap.c:(.text+0x28d): undefined reference to `ldap_memfree'
openldap.c:(.text+0x2e1): undefined reference to `ldap_get_option'
openldap.c:(.text+0x2fa): undefined reference to `ber_sockbuf_add_io'
openldap.c:(.text+0x343): undefined reference to `ldap_err2string'
openldap.c:(.text+0x373): undefined reference to `ldap_err2string'
../../../../thirdparty/installed//lib/libcurl.a(libcurl_la-openldap.o): In function `ldap_recv':
openldap.c:(.text+0x421): undefined reference to `ldap_result'
openldap.c:(.text+0x44a): undefined reference to `ldap_first_message'
openldap.c:(.text+0x497): undefined reference to `ldap_next_message'
openldap.c:(.text+0x4ab): undefined reference to `ldap_msgtype'
openldap.c:(.text+0x4d7): undefined reference to `ldap_get_dn_ber'
openldap.c:(.text+0x573): undefined reference to `ldap_get_attribute_ber'
openldap.c:(.text+0x851): undefined reference to `ber_memfree'
openldap.c:(.text+0x894): undefined reference to `ldap_get_attribute_ber'
openldap.c:(.text+0x8e5): undefined reference to `ber_free'
openldap.c:(.text+0x8fd): undefined reference to `ldap_msgfree'
openldap.c:(.text+0x945): undefined reference to `ldap_parse_result'
openldap.c:(.text+0x991): undefined reference to `ldap_memfree'
openldap.c:(.text+0x9a3): undefined reference to `ber_memfree'
openldap.c:(.text+0x9af): undefined reference to `ber_free'
openldap.c:(.text+0x9b9): undefined reference to `ldap_msgfree'
openldap.c:(.text+0x9e3): undefined reference to `ldap_err2string'
openldap.c:(.text+0xa18): undefined reference to `ldap_err2string'
openldap.c:(.text+0xa5a): undefined reference to `ldap_err2string'
../../../../thirdparty/installed//lib/libcurl.a(libcurl_la-openldap.o): In function `ldap_connect':
openldap.c:(.text+0xb39): undefined reference to `ldap_init_fd'
openldap.c:(.text+0xb44): undefined reference to `ldap_err2string'
openldap.c:(.text+0xb87): undefined reference to `ldap_set_option'
../../../../thirdparty/installed//lib/libcurl.a(libcurl_la-openldap.o): In function `ldap_done':
openldap.c:(.text+0xc0f): undefined reference to `ldap_abandon_ext'
../../../../thirdparty/installed//lib/libcurl.a(libcurl_la-openldap.o): In function `ldap_do':
openldap.c:(.text+0xc6f): undefined reference to `ldap_url_parse'
openldap.c:(.text+0xd18): undefined reference to `ldap_search_ext'
openldap.c:(.text+0xd25): undefined reference to `ldap_free_urldesc'
openldap.c:(.text+0xd32): undefined reference to `ldap_err2string'
../../../../thirdparty/installed//lib/libcurl.a(libcurl_la-openldap.o): In function `ldap_setup_connection':
openldap.c:(.text+0xdeb): undefined reference to `ldap_url_parse'
openldap.c:(.text+0xe5a): undefined reference to `ldap_pvt_url_scheme2proto'
openldap.c:(.text+0xe67): undefined reference to `ldap_free_urldesc'
collect2: error: ld returned 1 exit status
make[2]: *** [src/service/palo_be] Error 1
make[1]: *** [src/service/CMakeFiles/palo_be.dir/all] Error 2
make: *** [all] Error 2

**Comment by morningman** [comment]
请尝试下以下操作：
在 thirdparty/build-thirdparty.sh 脚本中，找到 buil_curl 方法， ./configure 的参数修改为：
./configure --prefix=$TP_INSTALL_DIR \
--without-ssl --without-libidn2 --disable-ldap

然后到该文件最下方，注释掉除了 build_curl 以外的其余 build_xxx 调用。

保存退出，重新执行 sh build-thirdparty.sh 来编译 curl。
编译完成后，重新编译palo，看看能否解决问题。

**Comment by liuzx32** [comment]
多谢大神指导，Palo源码顺利编译通过！
