### ISSUE TITLE
thirdparty中thrift编译失败

### ISSUE THREAD

**Issue by Chustmilan** [baidu/palo#92]
./configure:line 17095:syntax error near unexcepted token 'QT，'
请问怎么解决？

**Comment by morningman** [comment]
首先对照install.md 中常见问题，先检查下 pkg-config 是否安装以及版本是否正确，如果还不行。参照如下步骤：
1. 找到系统中的pkg.m4 (由pkg-config 安装包安装)文件并复制的thrift/aclocal目录下。 (pkg.m4由pkg-config 工具生成.如果你的目录/usr/share/aclocal下没有pkg.m4文件,说明你可能没有安装pkg-config.)
cp /usr/share/aclocal/pkg.m4 aclocal
2. 再次运行./bootstrap.sh 和./configure。（在 build-thirdparty.sh 中找到 build_thrift， 参照其中的参数来运行 booststrap 和 configure）

**Comment by Chustmilan** [comment]
pkg.m4复制过去，第一编译没过，第二次就ok了。。

**Comment by morningman** [comment]
运行./bootstrap.sh 和./configure 可能会冲掉那个目录。先关闭了，有问题再联系。

**Comment by Chustmilan** [comment]
好的 多谢！
